FROM nginx:1.19.3

# Install cron service
RUN apt-get update && apt-get install -y cron wget supervisor

# Add crontab file in the cron directory
COPY supervisord/*.conf /etc/supervisor/conf.d/
COPY crontab /etc/cron.d/sitemap

RUN mkdir -p /var/log/supervisor

# Create app directory
WORKDIR /usr/share/nginx/html

# Copy nginx vhost config
COPY default.conf /etc/nginx/conf.d/default.conf

# Compile source
COPY build /usr/share/nginx/html

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
