FROM nginx:1.19.3

# Install cron service
RUN apt-get update && apt-get install -y cron && apt-get install -y wget

# Add crontab file in the cron directory
COPY crontab /etc/cron.d/sitemap

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/sitemap

# Start service cron
COPY cronstart /usr/sbin
ENTRYPOINT ["cronstart"]

# Create app directory
WORKDIR /usr/share/nginx/html

# Copy nginx vhost config
COPY default.conf /etc/nginx/conf.d/default.conf

# Compile source
COPY build /usr/share/nginx/html
