---

all:
  children:
    build:
      hosts:
        localhost:
          ansible_connection: local

    latest:
      hosts:
        latest-tra:
          ansible_connection: local

    demo:
      hosts:
        demo-tra:
          ansible_connection: local

    live:
      hosts:
        live-tra:
          ansible_connection: local
    external:
      hosts:
        live-gl-tra:
          ansible_host: 10.10.10.150
          ansible_user: essentials
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    test:
      hosts:
      test-tra:
      ansible_connection: local

    tra:
      hosts:
      hiv-tra:
      ansible_host:
      ansible_user:

    traservers:
      children:
      latest:
      demo:
      live:
      tra:
      test:
