---

all:
  children:
    build:
      hosts:
        localhost:
          ansible_connection: local

    latest:
      hosts:
        latest-tra:
          ansible_connection: local

    demo:
      hosts:
        demo-tra:
          ansible_connection: local

    live:
      hosts:
        live-tra:
          ansible_connection: local

    test:
      hosts:
      test-tra:
      ansible_connection: local

    tra:
      hosts:
      hiv-tra:
      ansible_host:
      ansible_user:

    traservers:
      latest:
      demo:
      live:
      tra:
      test:
