---

version: '3'

networks:
  hiv-docker-net:

volumes:
  admin_service_db_data:
  therapist_service_db_data:
  patient_service_db_data:
  vn_patient_service_db_data:
  open_library_service_db_data:
  phone_service_db_data:
  keycloak_db_data:
  rocketchat_db_data:
  rocketchat_uploads:

services:
  proxy:
    image: traefik:v2.5
    networks:
      - hiv-docker-net
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
    - './config/docker/traefik-config.yaml:/etc/traefik/traefik.yaml'
    - './config/docker/ssl:/certs/'
    ports:
    - '80:80'
    - '443:443'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`local-traefik.wehost.asia`)"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.service=api@internal"
      - "traefik.http.services.proxy.loadbalancer.server.port=8080"

  ############ ###
  ### Keycloak ###
  ################
  keycloak:
    build: ../keycloak/
    networks:
      - hiv-docker-net
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      PROXY_ADDRESS_FORWARDING: 'true'
      JAVA_OPTS: '-Dkeycloak.profile.feature.scripts=enabled
                  -Dkeycloak.profile.feature.upload_scripts=enabled -server -Xms64m -Xmx512m
                  -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
                  -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true'
    depends_on:
      - keycloak_db

  keycloak_db:
    image: mysql:8.0
    networks:
      - hiv-docker-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - keycloak_db_data:/var/lib/mysql
      - ./config/mysql/keycloak_db/data_restore.sql:/docker-entrypoint-initdb.d/data_restore.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak

  ###########
  # Krakend #
  ###########
  krakend:
    image: docker.io/devopsfaith/krakend:2.1.3
    networks:
      - hiv-docker-net
    volumes:
      - ../krakend/config/krakend:/etc/krakend
    environment:
      FC_ENABLE: 1
      FC_SETTINGS: settings

  #############
  ### Client ###
  #############
  client_web_app:
    image: nginx:1.22.1
    networks:
      - hiv-docker-net
    volumes:
      - ./config/docker/client-webapp/default.conf:/etc/nginx/conf.d/default.conf
      #- ./config/docker/client-webapp/default_none_hi.conf:/etc/nginx/conf.d/default_none_hi.conf
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.client-webapp.tls=true'
      - 'traefik.http.routers.client-webapp.rule=Host(`local-hi-admin.wehost.asia`) || Host(`local-hi-therapist.wehost.asia`) || Host(`local-hi-patient.wehost.asia`) || Host(`local-nonhi-admin.wehost.asia`) || Host(`local-nonhi-therapist.wehost.asia`) || Host(`local-nonhi-patient.wehost.asia`) || Host(`local-hi-phone.wehost.asia`) || Host(`local-hi-library.wehost.asia`)'
      - 'traefik.http.routers.client-webapp.service=client-webapp'
      - 'traefik.http.services.client-webapp.loadbalancer.server.port=80'
      - "traefik.http.middlewares.serviceheaders.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.routers.client_web_app.middlewares=serviceheaders"

  #############
  ### Admin ###
  #############
  admin_web_app:
    image: node:14.17.6
    command:
      - npm
      - start
    working_dir: /usr/src/app
    volumes:
      - ../admin-web-app:/usr/src/app
    networks:
      - hiv-docker-net
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    depends_on:
      - keycloak
      - krakend

  admin_service:
    build: ../admin-service
    networks:
      - hiv-docker-net
    environment:
      LOCAL_USER_ID: ${USER_ID}
    volumes:
      - ../admin-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
      - ./config/service/queue-worker.conf:/etc/supervisor/conf.d/queue-worker.conf
    depends_on:
      - admin_service_db

  admin_service_db:
    image: docker.io/mysql:8.0
    networks:
      - hiv-docker-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - admin_service_db_data:/var/lib/mysql
      - ./config/mysql/admin_service_db/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
      - ./config/mysql/admin_service_db/data_restore.sql:/docker-entrypoint-initdb.d/data_restore.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin_service
      MYSQL_PASSWORD: admin_service
      MYSQL_DATABASE: admin_service

  #############
  ### Therapist ###
  #############
  therapist_web_app:
    image: node:14.17.6
    command:
      - npm
      - start
    working_dir: /usr/src/app
    volumes:
      - ../therapist-web-app:/usr/src/app
    networks:
      - hiv-docker-net
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    depends_on:
      - keycloak
      - krakend

  therapist_service:
    image: wehostasia/nginx-php:7.4
    networks:
      - hiv-docker-net
    environment:
      LOCAL_USER_ID: ${USER_ID}
    volumes:
      - ../therapist-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
      - keycloak
      - therapist_service_db

  therapist_service_db:
    image: docker.io/mysql:8.0
    networks:
      - hiv-docker-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - therapist_service_db_data:/var/lib/mysql
      - ./config/mysql/therapist_service_db/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
      - ./config/mysql/therapist_service_db/data_restore.sql:/docker-entrypoint-initdb.d/data_restore.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: therapist_service
      MYSQL_PASSWORD: therapist_service
      MYSQL_DATABASE: therapist_service

  ###################
  # Patient Service #
  ###################
  patient_service:
    image: wehostasia/nginx-php:7.4
    networks:
      - hiv-docker-net
    environment:
      LOCAL_USER_ID: ${USER_ID}
    volumes:
      - ../patient-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
      - patient_service_db

  patient_service_db:
    image: mysql:8.0
    networks:
      - hiv-docker-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - patient_service_db_data:/var/lib/mysql
      - ./config/mysql/patient_service_db/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
      - ./config/mysql/patient_service_db/data_restore.sql:/docker-entrypoint-initdb.d/data_restore.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: patient_service
      MYSQL_PASSWORD: patient_service
      MYSQL_DATABASE: patient_service

  ######################
  # VN Patient Service #
  ######################
  patient_vn_service:
    image: wehostasia/nginx-php:7.4
    networks:
      - hiv-docker-net
    environment:
      LOCAL_USER_ID: ${USER_ID}
    volumes:
      - ../patient-service:/var/www/html
      - ../patient-service/.env.example.vn:/var/www/html/.env
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
      - vn_patient_service_db

  vn_patient_service_db:
    image: mysql:8.0
    networks:
      - hiv-docker-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - vn_patient_service_db_data:/var/lib/mysql
      - ./config/mysql/patient_service_db/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
      - ./config/mysql/vn_patient_service_db/data_restore.sql:/docker-entrypoint-initdb.d/data_restore.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: patient_service
      MYSQL_PASSWORD: patient_service
      MYSQL_DATABASE: patient_service

  ######################
  # Phone Service #
  ######################
  phone_service:
    image: wehostasia/nginx-php:7.4
    networks:
      - hiv-docker-net
    environment:
      LOCAL_USER_ID: ${USER_ID}
    volumes:
      - ../phone-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
      - phone_service_db

  phone_service_db:
    image: mysql:8.0
    networks:
      - hiv-docker-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - phone_service_db_data:/var/lib/mysql
      - ./config/mysql/phone_service_db/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
      - ./config/mysql/phone_service_db/data_restore.sql:/docker-entrypoint-initdb.d/data_restore.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: phone_service
      MYSQL_PASSWORD: phone_service
      MYSQL_DATABASE: phone_service

  #############
  ### Open Library ###
  #############
  library_web_app:
    image: node:14.17.6
    command:
      - npm
      - start
    working_dir: /usr/src/app
    volumes:
      - ../open-library-web-app:/usr/src/app
    networks:
      - hiv-docker-net
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    depends_on:
      - keycloak
      - krakend

  library_service:
    build: ../open-library-service/
    environment:
      LOCAL_USER_ID: ${USER_ID}
    volumes:
      - ../open-library-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
    networks:
      - hiv-docker-net
    depends_on:
      - keycloak
      - open_library_service_db

  open_library_service_db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - open_library_service_db_data:/var/lib/mysql
      - ./config/mysql/open_library_service_db/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
      - ./config/mysql/open_library_service_db/data_restore.sql:/docker-entrypoint-initdb.d/data_restore.sql
    networks:
      - hiv-docker-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: open_library_service
      MYSQL_PASSWORD: open_library_service
      MYSQL_DATABASE: open_library_service

  #############
  ### Rocket Chat ###
  #############
  rocketchat:
    image: rocketchat/rocket.chat:5.2.0
    volumes:
      - rocketchat_uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=https://local-hi-chat.wehost.asia
      - MONGO_URL=mongodb://mongo:27017/rocketchat?directConnection=true
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs0&directConnection=true
      - MAIL_URL=smtp://smtp.email
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.rocketchat.tls=true'
      - 'traefik.http.routers.rocketchat.rule=Host(`local-hi-chat.wehost.asia`)'
      - 'traefik.http.routers.rocketchat.service=rocketchat'
      - 'traefik.http.services.rocketchat.loadbalancer.server.port=3000'
    networks:
      - hiv-docker-net
    stdin_open: true
    tty: true
    depends_on:
      - mongo

  mongo:
    image: bitnami/mongodb:4.4.15
    volumes:
      - rocketchat_db_data:/bitnami/mongodb
    networks:
      - hiv-docker-net
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_INITIAL_PRIMARY_HOST: mongo
      ALLOW_EMPTY_PASSWORD: 'yes'

  # This container's job is for accessing database via user interface
  adminer:
    image: library/adminer:4.7.8
    networks:
      - hiv-docker-net
    ports:
      - "8060:8080"
