# -----------------------------------------------------------------------
x-superset-image: &superset-image apache/superset:4.1.1
x-redis-image: &redis-image redis:7.4.1
x-postgres-image: &postgres-image postgres:17.2

x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes:
  &superset-volumes # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./config/docker/superset:/app/docker
  - superset_home:/app/superset_home
  - ./config/docker/superset/superset_config.py:/app/pythonpath/superset_config.py
  - ./config/docker/superset/translations:/app/superset/translations
  - ./config/docker/superset/scripts:/app/superset-frontend/scripts

volumes:
  superset_home:
    external: false
  pg_home:
    external: false
  redis:
    external: false

networks:
  docker-net:
    name: docker-net
    external: true
# -----------------------------------------------------------------------

services:
  redis:
    image: *redis-image
    container_name: superset_cache
    networks:
      - docker-net
    volumes:
      - redis:/data

  db:
    env_file:
      - path: config/docker/superset/default-env # default
        required: true
      - path: config/docker/superset/override-env # optional override
        required: false
    image: *postgres-image
    container_name: superset_db
    networks:
      - docker-net
    volumes:
      - pg_home:/var/lib/postgresql/data
      - ./config/docker/superset/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  superset:
    env_file:
      - path: config/docker/superset/default-env # default
        required: true
      - path: config/docker/superset/override-env # optional override
        required: false
    image: *superset-image
    container_name: superset_app
    networks:
      - docker-net
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y nodejs &&
        apt-get install -y npm &&
        npm install -g po2json &&
        npm install -g prettier &&
        echo '✅ Node, npm, po2json, and prettier installed' &&
        chmod +x /app/superset-frontend/scripts/po2json.sh &&
        /app/docker/docker-bootstrap.sh app-gunicorn
      "
    user: "root"
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.superset.tls=true'
      - 'traefik.http.routers.superset.rule=Host(`local-hi-superset.wehost.asia`)'
      - 'traefik.http.routers.superset.service=superset'
      - 'traefik.http.services.superset.loadbalancer.server.port=8088'
      - "traefik.http.middlewares.serviceheaders.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.routers.client_web_app.middlewares=serviceheaders"

  superset-init:
    image: *superset-image
    container_name: superset_init
    networks:
      - docker-net
    command: ["/app/docker/docker-init.sh"]
    env_file:
      - path: config/docker/superset/default-env # default
        required: true
      - path: config/docker/superset/override-env # optional override
        required: false
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    networks:
      - docker-net
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file:
      - path: config/docker/superset/default-env # default
        required: true
      - path: config/docker/superset/override-env # optional override
        required: false
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]

  superset-worker-beat:
    image: *superset-image
    container_name: superset_worker_beat
    networks:
      - docker-net
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file:
      - path: config/docker/superset/default-env # default
        required: true
      - path: config/docker/superset/override-env # optional override
        required: false
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true
