---

version: '3'

services:
  #  admin_web_app:
  #    build: ../admin-web-app/
  #    stdin_open: true # docker run -i
  #    tty: true        # docker run -t
  #    volumes:
  #      - ../admin-web-app:/usr/src/app
  #
  #  therapist_web_app:
  #    build: ../therapist-web-app/
  #    stdin_open: true # docker run -i
  #    tty: true        # docker run -t
  #    volumes:
  #      - ../therapist-web-app:/usr/src/app

  #################
  # Admin Service #
  #################
  admin_service:
    image: rathaheang/nginx-php:7.4
    environment:
      LOCAL_USER_ID: 1001
    volumes:
      - ../admin-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
      - admin_service_db
    ports:
      - 8082:80

  admin_service_db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - admin_service_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin_service
      MYSQL_PASSWORD: admin_service
      MYSQL_DATABASE: admin_service

  #####################
  # Therapist Service #
  #####################
  therapist_service:
    image: rathaheang/nginx-php:7.4
    environment:
      LOCAL_USER_ID: 1001
    volumes:
      - ../therapist-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
      - therapist_service_db
    ports:
      - 8083:80

  therapist_service_db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - therapist_service_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: therapist_service
      MYSQL_PASSWORD: therapist_service
      MYSQL_DATABASE: therapist_service
    ports:
      - 3307:3306

  ###################
  # Patient Service #
  ###################
  patient_service:
    image: rathaheang/nginx-php:7.4
    environment:
      LOCAL_USER_ID: 1001
    volumes:
      - ../patient-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
      - patient_service_db
    ports:
      - 8084:80

  patient_service_db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - patient_service_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: patient_service
      MYSQL_PASSWORD: patient_service
      MYSQL_DATABASE: patient_service
    ports:
      - 3308:3306

  ###########
  # Krakend #
  ###########
  krakend:
    image: devopsfaith/krakend:1.1.1
    volumes:
      - ./config/krakend:/etc/krakend
    depends_on:
      - admin_service
      - therapist_service
      - patient_service

  ############
  # Keycloak #
  ############
  keycloak:
    build: ../keycloak/
    ports:
      - 8080:8080
    volumes:
      - ../keycloak/themes/hi:/opt/jboss/keycloak/themes/hi
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      JAVA_OPTS: '-Dkeycloak.profile.feature.scripts=enabled
                  -Dkeycloak.profile.feature.upload_scripts=enabled -server -Xms64m -Xmx512m
                  -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
                  -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true'
    depends_on:
      - keycloak_db

  keycloak_db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - keycloak_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
    ports:
      - 3306:3306

  ###############
  # Rocket chat #
  ###############
  rocketchat:
    image: rocketchat/rocket.chat:3.6.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    volumes:
      - rocketchat_uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.email
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo:3.6.9
    volumes:
      - rocketchat_db_data:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:3.6.9
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo

  #########
  # Proxy #
  #########
  proxy:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./config/proxy/default-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - keycloak
      - krakend
#      - admin_web_app
#      - therapist_web_app

  # This container's job is for accessing database via user interface
  adminer:
    image: library/adminer:4.7.8
    ports:
      - 8060:8080

volumes:
  admin_service_db_data:
  therapist_service_db_data:
  patient_service_db_data:
  keycloak_db_data:
  rocketchat_db_data:
  rocketchat_uploads:
