---

version: '3'

networks:
  hiv-docker-net:
  meet.jitsi:

volumes:
  admin_service_db_data:
  therapist_service_db_data:
  patient_service_db_data:
  vn_patient_service_db_data:
  open_library_service_db_data:
  keycloak_db_data:
  rocketchat_db_data:
  rocketchat_uploads:

services:
  proxy:
    image: traefik:v2.5
    networks:
      - hiv-docker-net
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
    - './config/docker/traefik-config.yaml:/etc/traefik/traefik.yaml'
    - './config/docker/ssl:/certs/'
    ports:
    - '80:80'
    - '443:443'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`local-traefik.wehost.asia`)"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.service=api@internal"
      - "traefik.http.services.proxy.loadbalancer.server.port=8080"

  ############ ###
  ### Keycloak ###
  ################
  keycloak:
    build: ../keycloak/
    networks:
      - hiv-docker-net
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      PROXY_ADDRESS_FORWARDING: 'true'
      JAVA_OPTS: '-Dkeycloak.profile.feature.scripts=enabled
                  -Dkeycloak.profile.feature.upload_scripts=enabled -server -Xms64m -Xmx512m
                  -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
                  -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true'
    depends_on:
      - keycloak_db

  keycloak_db:
    image: mysql:8.0
    networks:
      - hiv-docker-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - keycloak_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak

  ###########
  # Krakend #
  ###########
  krakend:
    image: docker.io/devopsfaith/krakend:1.1.1
    networks:
      - hiv-docker-net
    volumes:
      - ../krakend/config/krakend:/etc/krakend
    environment:
      FC_ENABLE: 1
      FC_SETTINGS: settings

  #############
  ### Client ###
  #############
  client_web_app:
    image: nginx:1.19.3
    networks:
      - hiv-docker-net
    volumes:
      - ./config/docker/client-webapp/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.client-webapp.tls=true'
      - 'traefik.http.routers.client-webapp.rule=Host(`local-hi-admin.wehost.asia`) || Host(`local-hi-therapist.wehost.asia`) || Host(`local-hi-patient.wehost.asia`) || Host(`local-nonhi-admin.wehost.asia`) || Host(`local-nonhi-therapist.wehost.asia`) || Host(`local-nonhi-patient.wehost.asia`) || Host(`local-library.wehost.asia`)'
      - 'traefik.http.routers.client-webapp.service=client-webapp'
      - 'traefik.http.services.client-webapp.loadbalancer.server.port=80'

  #############
  ### Admin ###
  #############
  admin_web_app:
    image: node:14.17.6
    command:
      - npm
      - start
    working_dir: /usr/src/app
    volumes:
      - ../admin-web-app:/usr/src/app
    networks:
      - hiv-docker-net
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    depends_on:
      - keycloak
      - krakend

  admin_service:
    build: ../admin-service
    networks:
      - hiv-docker-net
    environment:
      LOCAL_USER_ID: 1001
    volumes:
      - ../admin-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
      - admin_service_db
    ports:
      - "8082:80"

  admin_service_db:
    image: docker.io/mysql:8.0
    networks:
      - hiv-docker-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - admin_service_db_data:/var/lib/mysql
      - ./config/mysql/admin_service_db/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYS0L_USER: admin_service
      MYSQL_PASSWORD: admin_service
      MYSQL_DATABASE: admin_service

  #############
  ### Therapist ###
  #############
  therapist_web_app:
    image: node:14.17.6
    command:
      - npm
      - start
    working_dir: /usr/src/app
    volumes:
      - ../therapist-web-app:/usr/src/app
    networks:
      - hiv-docker-net
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    depends_on:
      - keycloak
      - krakend

  therapist_service:
    image: rathaheang/nginx-php:7.4
    networks:
      - hiv-docker-net
    environment:
      LOCAL_USER_ID: 1001
    volumes:
      - ../therapist-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
      - keycloak
      - therapist_service_db
    ports:
      - "8083:80"

  therapist_service_db:
    image: docker.io/mysql:8.0
    networks:
      - hiv-docker-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - therapist_service_db_data:/var/lib/mysql
      - ./config/mysql/therapist_service_db/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: therapist_service
      MYSQL_PASSWORD: therapist_service
      MYSQL_DATABASE: therapist_service

  ###################
  # Patient Service #
  ###################
  patient_service:
    image: rathaheang/nginx-php:7.4
    networks:
      - hiv-docker-net
    environment:
      LOCAL_USER_ID: 1001
    volumes:
      - ../patient-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
      - patient_service_db
    ports:
      - "8084:80"

  patient_service_db:
    image: mysql:8.0
    networks:
      - hiv-docker-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - patient_service_db_data:/var/lib/mysql
      - ./config/mysql/patient_service_db/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: patient_service
      MYSQL_PASSWORD: patient_service
      MYSQL_DATABASE: patient_service
    ports:
      - "3308:3306"

  ######################
  # VN Patient Service #
  ######################
  patient_vn_service:
    image: rathaheang/nginx-php:7.4
    networks:
      - hiv-docker-net
    environment:
      LOCAL_USER_ID: 1001
    volumes:
      - ../patient-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
      - ../patient-service/.env_vn:/var/www/html/.env
    depends_on:
      - vn_patient_service_db
    ports:
      - "8086:80"

  vn_patient_service_db:
    image: mysql:8.0
    networks:
      - hiv-docker-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - vn_patient_service_db_data:/var/lib/mysql
      - ./config/mysql/patient_service_db/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: patient_service
      MYSQL_PASSWORD: patient_service
      MYSQL_DATABASE: patient_service
    ports:
      - "3310:3306"

  #############
  ### Open Library ###
  #############
  library_web_app:
    image: node:14.17.6
    command:
      - npm
      - start
    working_dir: /usr/src/app
    volumes:
      - ../open-library-web-app:/usr/src/app
    networks:
      - hiv-docker-net
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    depends_on:
      - keycloak
      - krakend

  library_service:
    build: ../open-library-service/
    environment:
      LOCAL_USER_ID: 1001
    volumes:
      - ../open-library-service:/var/www/html
      - ./config/service/default.conf:/etc/nginx/sites-available/default
      - ./config/service/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
      - keycloak
      - open_library_service_db
    ports:
      - "8085:80"

  open_library_service_db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - open_library_service_db_data:/var/lib/mysql
      - ./config/mysql/open_library_service_db/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: open_library_service
      MYSQL_PASSWORD: open_library_service
      MYSQL_DATABASE: open_library_service

  #############
  ### Rocket Chat ###
  #############
  rocketchat:
    image: rocketchat/rocket.chat:3.12.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    volumes:
      - rocketchat_uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=https://local-hi-chat.wehost.asia
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.email
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.rocketchat.tls=true'
      - 'traefik.http.routers.rocketchat.rule=Host(`local-hi-chat.wehost.asia`)'
      - 'traefik.http.routers.rocketchat.service=rocketchat'
      - 'traefik.http.services.rocketchat.loadbalancer.server.port=3000'
    networks:
      - hiv-docker-net
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  mongo:
    image: mongo:3.6.9
    volumes:
      - rocketchat_db_data:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    networks:
      - hiv-docker-net

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:3.6.9
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo

  # This container's job is for accessing database via user interface
  adminer:
    image: library/adminer:4.7.8
    networks:
      - hiv-docker-net
    ports:
      - "8060:8080"
