FROM {{ service_docker_image }}

ADD . /var/www
COPY default.conf /etc/nginx/conf.d/default.conf
COPY queue-worker.conf /etc/supervisor/conf.d/queue-worker.conf
COPY hi-task-scheduler /etc/cron.d/hi-task-scheduler
RUN touch /var/www/storage/logs/laravel.log
RUN chown -R www-data:www-data /var/www
RUN chmod 0644 /etc/cron.d/hi-task-scheduler

RUN apt-get update -y && apt-get install ffmpeg -y
