FROM {{ service_docker_image }}

ADD . /var/www
COPY default.conf /etc/nginx/conf.d/default.conf
COPY hi-task-scheduler /etc/cron.d/hi-task-scheduler
COPY queue-worker.conf /etc/supervisor/conf.d/queue-worker.conf
RUN touch /var/www/storage/logs/laravel.log
RUN chown -R www-data:www-data /var/www
