FROM wehostasia/laravel:nginx-php-8.3

ADD . /var/www
COPY default.conf /etc/nginx/conf.d/default.conf
COPY hi-task-scheduler /etc/cron.d/hi-task-scheduler
COPY queue-worker.conf /etc/supervisor/conf.d/queue-worker.conf
RUN chown -R www-data:www-data /var/www

RUN apt-get update -y && apt-get install ffmpeg -y && apt install imagemagick -y

# Modify ImageMagick policy to allow PDF conversion
RUN sed -i 's#<policy domain="coder" rights="none" pattern="PDF" />#<policy domain="coder" rights="read|write" pattern="PDF" />#' /etc/ImageMagick-6/policy.xml
