---

rocketchat_service: 'https://{{ stage }}-chat-rehabilitation.wehost.asia'

smtp_host:                              'email-smtp.us-east-1.amazonaws.com'
smtp_port:                              '587'
smtp_encryption:                        'tls'
smtp_mail_from_address:                 'noreply@opentelerehab.com'
