---

ssh_user:                     'ubuntu'
root_domain:                  'opentelerehab.com'
admin_webapp_url:             'admin.{{ root_domain }}'
therapist_webapp_url:         'therapist.{{ root_domain }}'
hicadmin_webapp_url:          'library.{{ root_domain }}'
rocketchat_url:               'chat.{{ root_domain }}'
jitsi_url:                    'meet.{{ root_domain }}'

keycloak_service:             'keycloak:8080'
admin_service:                'admin_service'
therapist_service:            'therapist_service'
patient_service:              'patient_service'
hicadmin_service:             'library_service'
rocketchat_service:           'http://rocketchat:3000'
krakend_service:              'krakend'
vn_patient_service:           'vn_patient_service'
vn_patient_host:              '103.229.42.86'
phone_service:                'phone_service'

my_host:                      'production-db.cwgm5sdsswey.ap-southeast-1.rds.amazonaws.com'
my_adminservice_user:         'admin_service'
my_adminservice_db:           'admin_service'
my_adminservice_pass:         '{{ my_adminservice_pass_vault }}'

my_therapistservice_user:     'therapist_service'
my_therapistservice_db:       'therapist_service'
my_therapistservice_pass:     '{{ my_therapistservice_pass_vault }}'

my_patientservice_user:       'patient_service'
my_patientservice_db:         'patient_service'
my_patientservice_pass:       '{{ my_patientservice_pass_vault }}'

my_hicadminservice_user:      'library_service'
my_hicadminservice_db:        'library_service'
my_hicadminservice_pass:      '{{ my_hicadminservice_pass_vault }}'

my_phoneservice_user:         'phone_service'
my_phoneservice_db:           'phone_service'
my_phoneservice_pass:         '{{ my_phoneservice_pass_vault }}'

mysql_name_keycloak:          'keycloak_service'
mysql_user_keycloak:          'keycloak_service'
mysql_pass_keycloak:          '{{ mysql_pass_keycloak_vault }}'
keycloak_admin_pass:          '{{ keycloak_admin_pass_vault }}'

rocketchat_admin_user_id:     '{{ rocketchat_admin_user_id_vault }}'
rocketchat_admin_auth_token:  '{{ rocketchat_admin_auth_token_vault }}'
rocketchat_admin_pass:        '{{ rocketchat_admin_pass_vault }}'

google_translate_api_key:     '{{ google_translate_api_key_vault }}'
