---

- name: Create deploy directory
  file:
    path: '{{ workspace }}/k8s-deploy'
    state: directory

- name: Create namespace and configmap
  template:
    src: '{{ item }}'
    dest: '{{ workspace }}/k8s-deploy/{{ item | basename | regex_replace("\.j2$", "") }}'
  with_fileglob:
    - '../templates/internal/*.j2'

### Deploy namespace and configmap

- name: Deploy namespace and configmap
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl apply -f {{ workspace }}/k8s-deploy/{{ item }}'
  loop:
    - namespace.yml
    - configmap.yml
  when: lookup('env', 'JENKINS_HOME')

### Deploy keycloak

- name: Deploy keycloak
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl apply -f {{ workspace }}/k8s-deploy/keycloak.yml'
  when: lookup('env', 'JENKINS_HOME')

### Deploy Admin Webapp

- name: Deploy admin webapp
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl apply -f {{ workspace }}/k8s-deploy/admin_webapp.yml'
  when: lookup('env', 'JENKINS_HOME')
