---

# Admin Service
- name: AdminService | Clone Admin service repos
  git:
    repo: git@git.web-essentials.asia:hiv-tra-20/admin-service.git
    dest: '{{ workspace }}/admin-service'
    accept_hostkey: yes
    version: master
    force: yes

# Admin Webapp
- name: AdminWebapp | Clone Admin webapp repos
  git:
    repo: git@git.web-essentials.asia:hiv-tra-20/admin-web-app.git
    dest: '{{ workspace }}/admin-webapp'
    accept_hostkey: yes
    version: master
    force: yes

- name: AdminWebapp | Create env
  template:
    src: 'internal/admin-webapp/.env.j2'
    dest: '{{ workspace }}/admin-webapp/.env'
    mode: 0755
  register: admin_webapp_env

- name: Create build file when env changed
  file:
    path: '/var/tmp/{{ project_id }}/{{ item }}'
    state: touch
    mode: 0755
  loop:
    - latest-admin-webapp-build
    - demo-admin-webapp-build
  when: admin_webapp_env.changed

# Therapist Service
- name: TherapistService | Clone therapist service repos
  git:
    repo: git@git.web-essentials.asia:hiv-tra-20/therapist-service.git
    dest: '{{ workspace }}/therapist-service'
    accept_hostkey: yes
    version: master
    force: yes

# Therapist Webapp
- name: TherapistWebapp | Clone Therapist webapp repos
  git:
    repo: git@git.web-essentials.asia:hiv-tra-20/therapist-web-app.git
    dest: '{{ workspace }}/therapist-webapp'
    accept_hostkey: yes
    version: master
    force: yes

- name: TherapistWebapp | Create env
  template:
    src: 'internal/therapist-webapp/.env.j2'
    dest: '{{ workspace }}/therapist-webapp/.env'
    mode: 0755
  register: therapist_webapp_env

- name: Create build file when env changed
  file:
    path: '/var/tmp/{{ project_id }}/{{ item }}'
    state: touch
    mode: 0755
  loop:
    - latest-therapist-webapp-build
    - demo-therapist-webapp-build
  when: therapist_webapp_env.changed

# Patient Service
- name: PatientService | Clone Admin service repos
  git:
    repo: git@git.web-essentials.asia:hiv-tra-20/patient-service.git
    dest: '{{ workspace }}/patient-service'
    accept_hostkey: yes
    version: master
    force: yes
