---

- name: AdminService | Clone Admin service repos
  git:
    repo: git@git.web-essentials.asia:hiv-tra-20/admin-service.git
    dest: '{{ workspace }}/admin-service'
    accept_hostkey: yes
    version: master
    force: yes
  when: admin_service_build.stat.exists

- name: AdminWebapp | Clone Admin webapp repos
  git:
    repo: git@git.web-essentials.asia:hiv-tra-20/admin-web-app.git
    dest: '{{ workspace }}/admin-webapp'
    accept_hostkey: yes
    version: master
    force: yes
  when: admin_webapp_build.stat.exists

- name: TherapistService | Clone therapist service repos
  git:
    repo: git@git.web-essentials.asia:hiv-tra-20/therapist-service.git
    dest: '{{ workspace }}/therapist-service'
    accept_hostkey: yes
    version: master
    force: yes
  when: therapist_service_build.stat.exists

- name: TherapistWebapp | Clone Therapist webapp repos
  git:
    repo: git@git.web-essentials.asia:hiv-tra-20/therapist-web-app.git
    dest: '{{ workspace }}/therapist-webapp'
    accept_hostkey: yes
    version: master
    force: yes
  when: therapist_webapp_build.stat.exists

# Patient Service
- name: PatientService | Clone Admin service repos
  git:
    repo: git@git.web-essentials.asia:hiv-tra-20/patient-service.git
    dest: '{{ workspace }}/patient-service'
    accept_hostkey: yes
    version: master
    force: yes
  when: patient_service_build.stat.exists

# Krakend Service
- name: KrakendService | Clone Krakend service repos
  git:
    repo: git@git.web-essentials.asia:hiv-tra-20/krakend.git
    dest: '{{ workspace }}/krakend-service'
    accept_hostkey: yes
    version: master
    force: yes
  when: krakend_service_build.stat.exists
