---

- name: Login to nexus docker private repo
  docker_login:
    registry: '{{ hub_registry }}'
    username: '{{ hub_user }}'
    password: '{{ hub_pass }}'

- name: Create deploy directory
  file:
    path: '{{ workspace }}/k8s-deploy'
    state: directory

- name: Create namespace and configmap
  template:
    src: '{{ item }}'
    dest: '{{ workspace }}/k8s-deploy/{{ item | basename | regex_replace("\.j2$", "") }}'
  with_fileglob:
    - '../templates/internal/k8s_deploy/*.j2'

### Deploy namespace and configmap

- name: Deploy namespace and configmap
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl apply -f {{ workspace }}/k8s-deploy/{{ item }}'
  loop:
    - namespace.yml
    - configmap.yml
    - pvc.yml
  when: lookup('env', 'JENKINS_HOME')
