---

### Admin Service
- name: Admin-Service | Wait until container ready
  shell: |
    while [[ $(kubectl -n {{ k8s_namespace }} get po -l app=app-{{ stage }}-{{ project_name }}-admin-service -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]] ; do echo "waiting for pod" && sleep 1 ; done
  args:
    executable: /bin/bash

- name: Admin-Service | Get running admin service pod name
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl get pods -n {{ k8s_namespace }} | grep app-{{ stage }}-{{ project_name }}-admin-service | cut -d " " -f1'
  register: admin_pod_name

- name: Admin-Service | Migrate DB
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ admin_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan migrate --force &'

- name: Admin-Service | Link storage folder to public
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ admin_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan storage:link &'

- name: Admin-Service | Change permission
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ admin_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/chmod -R 0777 /var/www/storage/ &'

- name: Admin-Service | Clear caches
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ admin_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan {{ item }} &'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear

- name: Admin-Service | Import default system settings
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ admin_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan {{ item }} &'
  loop:
    - hi:import-default-translation
    - hi:import-system-limit

### Therapist Service

- name: Therapist-Service | Wait until container ready
  shell: |
    while [[ $(kubectl -n {{ k8s_namespace }} get po -l app=app-{{ stage }}-{{ project_name }}-therapist-service -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]] ; do echo "waiting for pod" && sleep 1 ; done
  args:
    executable: /bin/bash

- name: Therapist-Service | Get running admin service pod name
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl get pods -n {{ k8s_namespace }} | grep app-{{ stage }}-{{ project_name }}-therapist-service | cut -d " " -f1'
  register: therapist_pod_name

- name: Therapist-Service | Migrate DB
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ therapist_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan migrate --force &'

- name: Therapist-Service | Link storage folder to public
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ therapist_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan storage:link &'

- name: Therapist-Service | Change permission
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ therapist_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/chmod -R 0777 /var/www/storage/ &'

- name: Therapist-Service | Clear caches
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ therapist_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan {{ item }} &'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear

### Patient Service
- name: Patient-Service | Wait until container ready
  shell: |
    while [[ $(kubectl -n {{ k8s_namespace }} get po -l app=app-{{ stage }}-{{ project_name }}-patient-service -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]] ; do echo "waiting for pod" && sleep 1 ; done
  args:
    executable: /bin/bash

- name: Patient-Service | Get running patient service pod name
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl get pods -n {{ k8s_namespace }} | grep app-{{ stage }}-{{ project_name }}-patient-service | cut -d " " -f1'
  register: patient_pod_name

- name: Patient-Service | Migrate DB
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ patient_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan migrate --force &'

- name: Patient-Service | Link storage folder to public
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ patient_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan storage:link &'

- name: Patient-Service | Change permission
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ patient_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/chmod -R 0777 /var/www/storage/ &'

- name: Patient-Service | Clear caches
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ patient_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan {{ item }} &'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear

### VN Patient Service
- name: VN-Patient-Service | Wait until container ready
  shell: |
    while [[ $(kubectl -n {{ k8s_namespace }} get po -l app=app-{{ stage }}-{{ project_name }}-vn-patient-service -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]] ; do echo "waiting for pod" && sleep 1 ; done
  args:
    executable: /bin/bash

- name: VN-Patient-Service | Get running patient service pod name
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl get pods -n {{ k8s_namespace }} | grep app-{{ stage }}-{{ project_name }}-vn-patient-service | cut -d " " -f1'
  register: vn_patient_pod_name

- name: VN-Patient-Service | Migrate DB
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ vn_patient_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan migrate --force &'

- name: VN-Patient-Service | Link storage folder to public
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ vn_patient_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan storage:link &'

- name: VN-Patient-Service | Change permission
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ vn_patient_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/chmod -R 0777 /var/www/storage/ &'

- name: VN-Patient-Service | Clear caches
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl exec {{ vn_patient_pod_name.stdout }} -n {{ k8s_namespace }} -- /usr/bin/php artisan {{ item }} &'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear
