---

- name: Production | Login to nexus docker private repo
  docker_login:
    registry: '{{ hub_registry }}'
    username: '{{ hub_user }}'
    password: '{{ hub_pass }}'
  delegate_to: live-gl-tra

- name: Production | Create projects directory global server
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  delegate_to: live-gl-tra
  loop:
    - projects/hiv/config
    - projects/hiv/config/admin-web-app
    - projects/hiv/config/adminservice/storage
    - projects/hiv/config/keycloak
    - projects/hiv/config/krakend
    - projects/hiv/config/patientservice/storage
    - projects/hiv/config/rocketchat
    - projects/hiv/config/therapist-web-app
    - projects/hiv/config/therapistservice/storage
    - projects/hiv/config/libraryservice/storage
    - projects/hiv/config/phoneservice/storage
    - projects/hiv/config/vn_patient/storage

- name: Production |  Add deployment files global server
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0755
  loop:
    - { src: 'external/docker-compose.yml.j2', dest: 'projects/hiv/docker-compose.yml' }
    - { src: 'external/vn-patient.yml.j2', dest: 'projects/hiv/vn-patient-compose.yml' }
    - { src: 'external/config/keycloak/theme.properties.j2', dest: 'projects/hiv/config/keycloak/theme.properties' }
    - { src: 'external/config/vn_patient/env.j2', dest: 'projects/hiv/config/vn_patient/env' }
  delegate_to: live-gl-tra

- name: Production | Sync storage
  shell: 'rsync -avz {{ item.src }} {{ item.dest }}'
  loop:
    - { src: '{{ workspace }}/admin-service/storage/', dest: 'ubuntu@54.179.65.28:/home/{{ ssh_user }}/projects/hiv/config/adminservice/storage/' }
    - { src: '{{ workspace }}/therapist-service/storage/', dest: 'ubuntu@54.179.65.28:/home/{{ ssh_user }}/projects/hiv/config/therapistservice/storage/' }
    - { src: '{{ workspace }}/hicadmin-service/storage/', dest: 'ubuntu@54.179.65.28:/home/{{ ssh_user }}/projects/hiv/config/libraryservice/storage/' }
    - { src: '{{ workspace }}/phone-service/storage/', dest: 'ubuntu@54.179.65.28:/home/{{ ssh_user }}/projects/hiv/config/phoneservice/storage/' }
    - { src: '{{ workspace }}/patient-service/storage/', dest: 'ubuntu@54.179.65.28:/home/{{ ssh_user }}/projects/hiv/config/patientservice/storage/' }
    - { src: '{{ workspace }}/patient-service/storage/', dest: 'ubuntu@54.179.65.28:/home/{{ ssh_user }}/projects/hiv/config/vn_patient/storage/' }

- name: Docker compose pull latest images
  shell: "docker-compose -f {{ item }} pull"
  args:
    chdir: 'projects/hiv'
  loop:
    - docker-compose.yml
    - vn-patient-compose.yml
  delegate_to: live-gl-tra

- name: Docker compose start all container
  shell: "docker-compose -f {{ item }} up -d"
  args:
    chdir: 'projects/hiv'
  loop:
    - docker-compose.yml
    - vn-patient-compose.yml
  delegate_to: live-gl-tra

- name: Wait for containers ready
  pause:
    seconds: 30

# Run artisan admin service
- name: Run artisan migration
  shell: 'docker-compose exec admin_service /usr/bin/php artisan migrate --force'
  args:
    chdir: 'projects/hiv'
  when: admin_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan storage link
  shell: 'docker-compose exec admin_service /usr/bin/php artisan storage:link'
  args:
    chdir: 'projects/hiv'
  when: admin_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan clear cache
  shell: 'docker-compose exec admin_service /usr/bin/php artisan {{ item }}'
  args:
    chdir: 'projects/hiv'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear
  when: admin_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan import
  shell: 'docker-compose exec admin_service /usr/bin/php artisan hi:import-default-translation'
  args:
    chdir: 'projects/hiv'
  when: admin_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan create backend user
  shell: 'docker-compose exec admin_service /usr/bin/php artisan hi:create-backend-user &'
  args:
    chdir: 'projects/hiv'
  when: admin_service_build.stat.exists
  delegate_to: live-gl-tra

# Run artisan therapist service
- name: Run artisan migration
  shell: 'docker-compose exec therapist_service /usr/bin/php artisan migrate --force'
  args:
    chdir: 'projects/hiv'
  when: therapist_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan storage link
  shell: 'docker-compose exec therapist_service /usr/bin/php artisan storage:link'
  args:
    chdir: 'projects/hiv'
  when: therapist_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan clear cache
  shell: 'docker-compose exec therapist_service /usr/bin/php artisan {{ item }}'
  args:
    chdir: 'projects/hiv'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear
  when: therapist_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan import
  shell: 'docker-compose exec therapist_service /usr/bin/php artisan hi:create-backend-user &'
  args:
    chdir: 'projects/hiv'
  when: therapist_service_build.stat.exists
  delegate_to: live-gl-tra

# Run artisan patient service
- name: Run artisan migration
  shell: 'docker-compose exec patient_service /usr/bin/php artisan migrate --force'
  args:
    chdir: 'projects/hiv'
  when: patient_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan storage link
  shell: 'docker-compose exec patient_service /usr/bin/php artisan storage:link'
  args:
    chdir: 'projects/hiv'
  when: patient_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan clear cache
  shell: 'docker-compose exec patient_service /usr/bin/php artisan {{ item }}'
  args:
    chdir: 'projects/hiv'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear
  when: patient_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan import
  shell: 'docker-compose exec patient_service /usr/bin/php artisan hi:create-backend-user &'
  args:
    chdir: 'projects/hiv'
  when: patient_service_build.stat.exists
  delegate_to: live-gl-tra

# Run artisan library service
- name: Run artisan migration
  shell: 'docker-compose exec library_service /usr/bin/php artisan migrate --force'
  args:
    chdir: 'projects/hiv'
  when: hicadmin_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan storage link
  shell: 'docker-compose exec library_service /usr/bin/php artisan storage:link'
  args:
    chdir: 'projects/hiv'
  when: hicadmin_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan clear cache
  shell: 'docker-compose exec library_service /usr/bin/php artisan {{ item }}'
  args:
    chdir: 'projects/hiv'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear
  when: hicadmin_service_build.stat.exists
  delegate_to: live-gl-tra

# Run artisan phone service
- name: Run artisan migration
  shell: 'docker-compose exec phone_service /usr/bin/php artisan migrate --force'
  args:
    chdir: 'projects/hiv'
  when: hicadmin_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan storage link
  shell: 'docker-compose exec phone_service /usr/bin/php artisan storage:link'
  args:
    chdir: 'projects/hiv'
  when: hicadmin_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan clear cache
  shell: 'docker-compose exec phone_service /usr/bin/php artisan {{ item }}'
  args:
    chdir: 'projects/hiv'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear
  delegate_to: live-gl-tra

### VIETNAME
- name: VN Patient | Run artisan migration
  shell: 'docker-compose -f vn-patient-compose.yml exec vn_patient_service /usr/bin/php artisan migrate --force'
  args:
    chdir: 'projects/hiv'
  when: patient_service_build.stat.exists
  delegate_to: live-gl-tra

- name: VN Patient | Run artisan storage link
  shell: 'docker-compose -f vn-patient-compose.yml exec vn_patient_service /usr/bin/php artisan storage:link'
  args:
    chdir: 'projects/hiv'
  when: patient_service_build.stat.exists
  delegate_to: live-gl-tra

- name: VN Patient | Run artisan clear cache
  shell: 'docker-compose -f vn-patient-compose.yml exec vn_patient_service /usr/bin/php artisan {{ item }}'
  args:
    chdir: 'projects/hiv'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear
  when: patient_service_build.stat.exists
  delegate_to: live-gl-tra

- name: Run artisan import
  shell: 'docker-compose -f vn-patient-compose.yml exec vn_patient_service /usr/bin/php artisan hi:create-backend-user &'
  args:
    chdir: 'projects/hiv'
  delegate_to: live-gl-tra

- name: Remove build file state
  file:
    path: '/var/tmp/{{ project_id }}/{{ item }}'
    state: absent
  loop:
    - '{{ stage }}-admin-service-build'
    - '{{ stage }}-admin-webapp-build'
    - '{{ stage }}-therapist-service-build'
    - '{{ stage }}-therapist-webapp-build'
    - '{{ stage }}-patient-service-build'
    - '{{ stage }}-krakend-service-build'
