---

- name: Production | Login to nexus docker private repo
  docker_login:
    registry: '{{ hub_registry }}'
    username: '{{ hub_user }}'
    password: '{{ hub_pass }}'
  delegate_to: live-gl-tra

- name: Production | Create projects directory
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  loop:
    - projects/hiv/config
    - projects/hiv/config/admin-web-app
    - projects/hiv/config/adminservice
    - projects/hiv/config/jitsi
    - projects/hiv/config/keycloak
    - projects/hiv/config/krakend
    - projects/hiv/config/patientservice
    - projects/hiv/config/rocketchat
    - projects/hiv/config/therapist-web-app
    - projects/hiv/config/therapistservice
  delegate_to: live-gl-tra

- name: Production |  Add deployment files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0755
  loop:
    - { src: 'external/docker-compose.yml.j2', dest: 'projects/hiv/docker-compose.yml' }
  delegate_to: live-gl-tra

- name: Production | Docker compose pull latest images
  shell: docker-compose pull
  args:
    chdir: 'projects/hiv'
  delegate_to: live-gl-tra

- name: Production | Docker compose start all container
  shell: docker-compose up -d
  args:
    chdir: 'projects/hiv'
  delegate_to: live-gl-tra
